<a href="https://colab.research.google.com/github/Melisacid/Act.7.1_Regresion_no_lineal/blob/main/Act_7_2_regresi%C3%B3n_log%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Actividad Grupal**
Melisa Hernandez Cid - A01732341

Alexa Bustamante de la Cruz A01173639



1. Utilizar el nuevo repositorio con el nombre: Regresión No Lineal y Regresión Logistica
2. Agregar el archivo: Gastos y costos 20-23.xlsx”
3. Realiza las acciones de preprocesamiento necesarias: Nulos y Outliers
4. Convertir la variable TIPO GASTO en una variable dicotómica con los valores: “COMPRAS” y “OTROS GASTOS” de la base de datos “Gatos y costos 20-23.xlsx” , para los años 2020, 2021, 2022 y 2023 aplicando la herramienta de  “Regresión Logística”
5. Analizar los siguientes casos de correlación logística que existe entre las siguientes variables:
TIPO GASTO (variable objetivo) y TOTAL MX (variable independente) de la base de datos “Gastos y costos 20-23.xlsx” , para los años 2020, 2021, 2022 y 2023 aplicando la herramienta de  “Regresión Logística”

6. Realizar una tabla de todos los coeficientes de precisión, exactitud y sensibilidad obtenidos para cada correlación analizada, según sea el caso.
7. Crear los archivos requeridos en Google Colab y respaldarlos en GitHub.
8 Generar un reporte comparativo sobre los análisis realizados y subirlo a GitHub, en formato pdf.
9. Subir el link del repositorio en CANVAS para “Evaluación”

In [ ]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

## **2020**

In [ ]:
#Carga desde un archivo .xlsx sin indice
df20= pd.read_excel('Gastos_costos_2020.xlsx')

In [ ]:
#Rellenamos nulos
df2020 =df20.fillna(method="bfill")
df2020 =df20.fillna(method="ffill")

In [ ]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(df2020['TIPO GASTO'])
unico

array(['ALIMENTOS', 'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL',
       'ATENCION CLIENTES', 'CALIBRACIONES', 'CAPACITACION',
       'COMBUSTIBLE', 'COMISION BANCARIA', 'COMISION VENTA', 'COMPRAS',
       'DERECHOS', 'ENERGIA ELECTRICA', 'FLETES', 'GERENCIA ADMON',
       'GERENCIA VTAS', 'HONORARIOS ADMON', 'HONORARIOS CONTABLES',
       'HONORARIOS PM', 'HOSPEDAJE', 'IMSS/INFONAVIT', 'MAQUILAS GIC',
       'MAQUINARIA', 'MEDICOS', 'MENSAJERIA', 'MOBILIARIO',
       'MTTO COMPUTO', 'MTTO LOCAL', 'MTTO TRANSPORTE', 'NO DEDUCIBLE',
       'PAPELERIA', 'PAQUETERIA', 'PEAJES', 'PUBLICIDAD',
       'REPARACIONES ELECTRICAS', 'SEGUROS', 'SERV FUNERARIO ',
       'SUBCONTRATOS', 'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE',
       'UNIFORME', 'VALES DESPENSA'], dtype=object)

In [ ]:
#Convierto una variable a dicotómica 
df2020['TIPO GASTO']= df2020['TIPO GASTO'].replace(['ALIMENTOS', 'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL',
       'ATENCION CLIENTES', 'CALIBRACIONES', 'CAPACITACION',
       'COMBUSTIBLE', 'COMISION BANCARIA', 'COMISION VENTA', 
       'DERECHOS', 'ENERGIA ELECTRICA', 'FLETES', 'GERENCIA ADMON',
       'GERENCIA VTAS', 'HONORARIOS ADMON', 'HONORARIOS CONTABLES',
       'HONORARIOS PM', 'HOSPEDAJE', 'IMSS/INFONAVIT', 'MAQUILAS GIC',
       'MAQUINARIA', 'MEDICOS', 'MENSAJERIA', 'MOBILIARIO',
       'MTTO COMPUTO', 'MTTO LOCAL', 'MTTO TRANSPORTE', 'NO DEDUCIBLE',
       'PAPELERIA', 'PAQUETERIA', 'PEAJES', 'PUBLICIDAD',
       'REPARACIONES ELECTRICAS', 'SEGUROS', 'SERV FUNERARIO ',
       'SUBCONTRATOS', 'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE',
       'UNIFORME', 'VALES DESPENSA'], "OTROS GASTOS")

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df2020["TOTAL MX"]
Var_Dep= df2020['TIPO GASTO']

In [ ]:
#Redefinimos las variables 
X2020= Vars_Indep
y2020= Var_Dep

In [ ]:
# Convierte el objeto Series en un array numpy y remodela los datos si tienen una sola característica
X2020 = X2020.values.reshape(-1, 1)

# Divide los datos en conjuntos de entrenamiento y prueba
X2020_train, X2020_test, y2020_train, y2020_test = train_test_split(X2020, y2020, test_size=0.3)

# Crea una instancia de StandardScaler y escala los datos de entrenamiento y prueba
escalar2020 = StandardScaler()
X2020_train = escalar2020.fit_transform(X2020_train)
X2020_test = escalar2020.transform(X2020_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X2020_train, y2020_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y2020_pred = algoritmo.predict(X2020_test) 
y2020_pred

array(['OTROS GASTOS', 'OTROS GASTOS', 'OTROS GASTOS', ...,
       'OTROS GASTOS', 'OTROS GASTOS', 'OTROS GASTOS'], dtype=object)

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz2020 = confusion_matrix(y2020_test, y2020_pred)
print('Matriz de Confusión:')
print(matriz2020)

Matriz de Confusión:
[[  0 437]
 [  1 565]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision2020 = precision_score(y2020_test, y2020_pred, average="binary", pos_label="COMPRAS")
print('Precisión del modelo:')
print(precision2020)

Precisión del modelo:
0.0


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud2020 = accuracy_score(y2020_test, y2020_pred)
print('Exactitud del modelo:')
print(exactitud2020)

Exactitud del modelo:
0.5633100697906281


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad2020 = recall_score(y2020_test, y2020_pred, average="binary", pos_label="COMPRAS")
print('Sensibilidad del modelo:')
print(sensibilidad2020)

Sensibilidad del modelo:
0.0


In [ ]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef12020 = f1_score(y2020_test, y2020_pred, average="binary", pos_label="COMPRAS")
print('Puntaje F1 del modelo:')
print(puntajef12020)

Puntaje F1 del modelo:
0.0


In [ ]:
# Crear un diccionario con los resultados
resultados = {'Exactitud': [exactitud2020],
              'Sensibilidad': [sensibilidad2020],
              'Precisión': [precision2020]}

# Convertir el diccionario en un DataFrame de pandas
tabla_resultados20 = pd.DataFrame(resultados)

# Establecer un índice descriptivo para la tabla
tabla_resultados20.index = ['Modelo 2020']

# Imprimir la tabla de resultados
print(tabla_resultados20)

             Exactitud  Sensibilidad  Precisión
Modelo 2020    0.56331           0.0        0.0


In [ ]:
# Carga desde un archivo .xlsx sin indice
df20 = pd.read_excel('Gastos_costos_2020.xlsx')

# Rellenamos nulos
df2020 = df20.fillna(method="bfill")
df2020 = df20.fillna(method="ffill")

# Convierto una variable a dicotómica
df2020['TIPO GASTO'] = df2020['TIPO GASTO'].apply(lambda x: 1 if x == 'COMPRAS' else 0)

# Declaramos las variables dependientes e independientes para la regresión Logística
X2020 = df2020["TOTAL MX"].values.reshape(-1, 1)
y2020 = df2020['TIPO GASTO']

# Divide los datos en conjuntos de entrenamiento y prueba
X2020_train, X2020_test, y2020_train, y2020_test = train_test_split(X2020, y2020, test_size=0.3)

# Crea una instancia de StandardScaler y escala los datos de entrenamiento y prueba
escalar2020 = StandardScaler()
X2020_train = escalar2020.fit_transform(X2020_train)
X2020_test = escalar2020.transform(X2020_test)

# Definimos el algoritmo a utilizar
algoritmo = LogisticRegression()

# Entrenamos el modelo
algoritmo.fit(X2020_train, y2020_train)

# Realizamos una predicción
y2020_pred = algoritmo.predict(X2020_test)

# Verifico la matriz de Confusión
matriz2020 = confusion_matrix(y2020_test, y2020_pred)
print('Matriz de Confusión:')
print(matriz2020)

# Calcular la precisión
precision = precision_score(y2020_test, y2020_pred)
print(f'Precisión: {precision}')

# Calcular la exactitud
exactitud = accuracy_score(y2020_test, y2020_pred)
print(f'Exactitud: {exactitud}')

# Calcular la sensibilidad (recall)
sensibilidad = recall_score(y2020_test, y2020_pred)
print(f'Sensibilidad: {sensibilidad}')

Matriz de Confusión:
[[568   1]
 [434   0]]
Precisión: 0.0
Exactitud: 0.5663010967098704
Sensibilidad: 0.0


## **2021**

In [ ]:
#Carga desde un archivo .xlsx sin indice
df21= pd.read_excel('Gastos_costos_2021.xlsx')
df21.head(5)

FECHA                   FOLIO                                  UUID  \
0 2021-01-01  0001010100750847116902  71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B   
1 2021-01-01  0001010100752163714102  B8AEDE83-CC76-404C-A611-6B5A87BA561F   
2 2021-01-01                   19788  19B9B2C2-DF58-E24D-B43A-3FC4D5A929E7   
3 2021-01-01                  211781  EAB26414-DD9A-4E8F-9F5C-05FE24D98E48   
4 2021-01-01                  211782  C16F79B5-FB35-4BFC-AF84-708B24F500BB   

            RFC                               PROVEEDOR  \
0  BNM840515VB1          BANCO NACIONAL DE MEXICO, S.A.   
1  BNM840515VB1          BANCO NACIONAL DE MEXICO, S.A.   
2  ESI9612311E7  ELECTRONICOS Y SIMILARES, S.A. DE C.V.   
3  BLE1512082R9            BEPENSA LEASING S.A. DE C.V.   
4  BLE1512082R9            BEPENSA LEASING S.A. DE C.V.   

                 TIPO GASTO  \
0         COMISION BANCARIA   
1         COMISION BANCARIA   
2                   COMPRAS   
3  ARRENDAMIENTO FINANCIERO   
4  ARRENDAMIENTO FINANCIERO   

                                         DESCRIPCION   MP   TC  IMPORTE  \
0                                   COMISION COBRADA  PUE  1.0   490.00   
1                                   COMISION COBRADA  PUE  1.0   345.00   
2                        MOTO E7 PLUS AZUL 64GB 4RAM  PUE  1.0  3447.41   
3  AA RENTA EXIGIBLE CL0000006876 6/36 de 03/12/2...  PPD  1.0  5551.38   
4  AA RENTA EXIGIBLE CL0000006877 6/36 de 03/12/2...  PPD  1.0  5551.98   

      IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT TIPO   STATUS POLIZA  
0   78.40      0.0      0.0     568.4      568.4    I  Vigente      0  
1   55.20      0.0      0.0     400.2      400.2    I  Vigente      0  
2  551.59      0.0      0.0    3999.0     3999.0    I  Vigente      0  
3  888.22      0.0      0.0    6439.6     6439.6    I  Vigente      0  
4  888.32      0.0      0.0    6440.3     6440.3    I  Vigente      0

In [ ]:
#Rellenamos nulos
df2021 =df21.fillna(method="bfill")
df2021 =df21.fillna(method="ffill")

In [ ]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(df2021['TIPO GASTO'])
unico

array(['ALIMENTOS', 'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL',
       'BOTIQUIN', 'CALIBRACIONES', 'CAPACITACION', 'COMBUSTIBLE ',
       'COMISION BANCARIA', 'COMISION MIXTA', 'COMPRA COMPUTADORA ',
       'COMPRA TABLET ', 'COMPRAS', 'COMPRAS ', 'DERECHOS',
       'ENERGIA ELECTRICA', 'FLETE', 'FLETES', 'GASOLINA',
       'GASTOS IMPORTACION ', 'GERENCIA ADMON', 'GERENCIA VTAS',
       'HONORARIOS CONTABLES', 'HONORARIOS JURIDICOS', 'HONORARIOS PF',
       'HONORARIOS PM', 'HOSPEDAJE', 'HOSPEDAJE ', 'IMSS/INFONAVIT',
       'MAQUILAS', 'MAQUILAS GIC', 'MAQUINARIA', 'MEDICOS', 'MENSAJERIA',
       'MONITOREO CAMARAS ADT', 'MTTO COMPUTO', 'MTTO LOCAL',
       'MTTO MAQUINARIA', 'MTTO OFICINA ', 'MTTO TRANSPORTE',
       'NO DEDUCIBLE', 'PAPELERIA', 'PAQUETERIA', 'PEAJES', 'PUBLICIDAD',
       'RENTA COPIADORA', 'RENTA OFICINA ', 'SANITIZACION', 'SEGUROS',
       'SUELDOS DIRECCION', 'SUELDOS PRODUCCION', 'SUELDOS VENTAS',
       'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE', 'UNIFO

In [ ]:
df2021['TIPO GASTO'] = df2021['TIPO GASTO'].apply(lambda x: 1 if x == 'COMPRAS' else 0)

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df2021["TOTAL MX"]
Var_Dep= df2021['TIPO GASTO']

In [ ]:
#Redefinimos las variables 
X2021= Vars_Indep
y2021= Var_Dep

In [ ]:
# Convierte el objeto Series en un array numpy y remodela los datos si tienen una sola característica
X2021 = X2021.values.reshape(-1, 1)

# Divide los datos en conjuntos de entrenamiento y prueba
X2021_train, X2021_test, y2021_train, y2021_test = train_test_split(X2021, y2021, test_size=0.3)

# Crea una instancia de StandardScaler y escala los datos de entrenamiento y prueba
escalar2021 = StandardScaler()
X2021_train = escalar2021.fit_transform(X2021_train)
X2021_test = escalar2021.transform(X2021_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X2021_train, y2021_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y2021_pred = algoritmo.predict(X2021_test) 
y2021_pred

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz2021 = confusion_matrix(y2021_test, y2021_pred)
print('Matriz de Confusión:')
print(matriz2021)

Matriz de Confusión:
[[115 356]
 [ 94 346]]


In [ ]:
print("Etiquetas únicas en y2021_test:", np.unique(y2021_test))
print("Etiquetas únicas en y2021_pred:", np.unique(y2021_pred))

Etiquetas únicas en y2021_test: [0 1]
Etiquetas únicas en y2021_pred: [0 1]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision2021 = precision_score(y2021_test, y2021_pred, average="binary", pos_label=1)
print('Precisión del modelo:')
print(precision2021)


Precisión del modelo:
0.4928774928774929


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud2021 = accuracy_score(y2021_test, y2021_pred)
print('Exactitud del modelo:')
print(exactitud2021)

Exactitud del modelo:
0.5060373216245884


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad2021 = recall_score(y2021_test, y2021_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo:')
print(sensibilidad2021)

Sensibilidad del modelo:
0.7863636363636364


In [ ]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef12021 = f1_score(y2021_test, y2021_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef12021)

Puntaje F1 del modelo:
0.6059544658493871


In [ ]:
# Crear un diccionario con los resultados
resultados = {'Exactitud': [exactitud2021],
              'Sensibilidad': [sensibilidad2021],
              'Precisión': [precision2021]}

# Convertir el diccionario en un DataFrame de pandas
tabla_resultados21 = pd.DataFrame(resultados)

# Establecer un índice descriptivo para la tabla
tabla_resultados21.index = ['Modelo 2021']

# Imprimir la tabla de resultados
print(tabla_resultados21)

             Exactitud  Sensibilidad  Precisión
Modelo 2021   0.506037      0.786364   0.492877


## **2022**

In [ ]:
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import SMOTE

In [ ]:
#Carga desde un archivo .xlsx sin indice
df22= pd.read_excel('Gastos_costos_2022.xlsx')

In [ ]:
#Rellenamos nulos
df22 =df22.fillna(method="bfill")
df22 =df22.fillna(method="ffill")

In [ ]:
#Verificar los valores sin repetirse de una columna
unico22 = np.unique(df22['TIPO GASTO'])
unico22

array(['ALIMENTOS', 'ANTICIPO ', 'ANTICIPO COMPRA AUTO',
       'ARRENDAMIENTO FINANCIERO', 'ARRENDAMIENTO LOCAL', 'CALIBRACIONES',
       'CAPACITACION', 'CASETAS', 'COMISION BANCARIA', 'COMISION MIXTA',
       'COMPRA AUTO ', 'COMPRAS', 'COMPRAS ', 'CREDITO ', 'DERECHOS',
       'ENERGIA ELECTRICA', 'FLETE', 'GASOLINA', 'GASTOS IMPORTACION ',
       'GERENCIA ADMON', 'HONORARIOS CONTABLES', 'HONORARIOS JURIDICOS',
       'HONORARIOS PM', 'HOSPEDAJE', 'IMSS/INFONAVIT',
       'INSTALACION ELECTRICA', 'MAQUILAS', 'MAQUINARIA', 'MEDICOS',
       'MENSAJERIA', 'MONITOREO CAMARAS ADT', 'MTTO COMPUTO',
       'MTTO EQUIPO COMPUTO', 'MTTO LOCAL', 'MTTO MAQUINARIA',
       'MTTO OFICINA ', 'MTTO TRANSPORTE', 'NO DEDUCIBLE', 'PAPELERIA',
       'PAQUETERIA', 'PEAJES', 'PUBLICIDAD', 'RENTA AUTO',
       'RENTA COPIADORA', 'SANITIZACION', 'SEGUROS', 'SUBCONTRATOS',
       'SUELDOS DIRECCION', 'SUSCRIPCIONES', 'TELEFONO', 'TRANSPORTE',
       'UNIFORMES', 'VALES DESPENSA', 'VARIOS'], dtype=objec

In [ ]:
df22['TIPO GASTO'] = df22['TIPO GASTO'].apply(lambda x: 1 if x == 'COMPRAS' else 0)

In [ ]:
#Redefinimos las variables 
X2022= Vars_Indep
y2022= Var_Dep

In [ ]:
# Definir las variables independientes y dependientes
X2022 = df22["TOTAL MX"].values.reshape(-1, 1)
y2022 = df22['TIPO GASTO']

# Aplicar SMOTE para equilibrar las clases
smote = SMOTE()
X2022_resampled, y2022_resampled = smote.fit_resample(X2022, y2022)

# Dividir los datos en conjuntos de entrenamiento y prueba
X2022_train, X2022_test, y2022_train, y2022_test = train_test_split(X2022_resampled, y2022_resampled, test_size=0.3)

# Escalar los datos
escalar2022 = StandardScaler()
X2022_train = escalar2022.fit_transform(X2022_train)
X2022_test = escalar2022.transform(X2022_test)

# Definir e instanciar el algoritmo
algoritmo = LogisticRegression(C=0.1, solver='liblinear')

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X2022_train, y2022_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y2022_pred = algoritmo.predict(X2022_test) 

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz2022 = confusion_matrix(y2022_test, y2022_pred)
print('Matriz de Confusión:')
print(matriz2022)

Matriz de Confusión:
[[105 310]
 [141 287]]


In [ ]:
print("Etiquetas únicas en y2022_test:", np.unique(y2022_test))
print("Etiquetas únicas en y2022_pred:", np.unique(y2022_pred))

Etiquetas únicas en y2022_test: [0 1]
Etiquetas únicas en y2022_pred: [0 1]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision2022 = precision_score(y2022_test, y2022_pred, average="binary", pos_label=1)
print('Precisión del modelo:')
print(precision2022)

Precisión del modelo:
0.4807370184254606


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud2022 = accuracy_score(y2022_test, y2022_pred)
print('Exactitud del modelo:')
print(exactitud2022)

Exactitud del modelo:
0.465005931198102


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad2022 = recall_score(y2022_test, y2022_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo:')
print(sensibilidad2022)

Sensibilidad del modelo:
0.6705607476635514


In [ ]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef12022 = f1_score(y2022_test, y2022_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef12022)

Puntaje F1 del modelo:
0.5599999999999999


In [ ]:

# Crear un diccionario con los resultados
resultados = {'Exactitud': [exactitud2022],
              'Sensibilidad': [sensibilidad2022],
              'Precisión': [precision2022]}

# Convertir el diccionario en un DataFrame de pandas
tabla_resultados22 = pd.DataFrame(resultados)

# Establecer un índice descriptivo para la tabla
tabla_resultados22.index = ['Modelo 2022']

# Imprimir la tabla de resultados
print(tabla_resultados22)


             Exactitud  Sensibilidad  Precisión
Modelo 2022   0.465006      0.670561   0.480737


## **2023**

In [ ]:
# Carga de datos
df23 = pd.read_excel('Gastos_costos_2023.xlsx')
df23 = df23.fillna(method="bfill")
df23 = df23.fillna(method="ffill")

# Preprocesamiento de datos
df23['TIPO GASTO'] = df23['TIPO GASTO'].apply(lambda x: 1 if x == 'COMPRAS' else 0)
X2023 = df23["TOTAL MX"].values.reshape(-1, 1)
y2023 = df23['TIPO GASTO']

# Aplicar SMOTE para equilibrar las clases
smote = SMOTE()
X2023_resampled, y2023_resampled = smote.fit_resample(X2023, y2023)

# Dividir los datos en conjuntos de entrenamiento y prueba
X2023_train, X2023_test, y2023_train, y2023_test = train_test_split(X2023_resampled, y2023_resampled, test_size=0.3)

# Escalar los datos
escalar2023 = StandardScaler()
X2023_train = escalar2023.fit_transform(X2023_train)
X2023_test = escalar2023.transform(X2023_test)

# Definir e instanciar el algoritmo
algoritmo = LogisticRegression(C=1.0, solver='liblinear')

# Entrenar el modelo
algoritmo.fit(X2023_train, y2023_train)

# Realizar predicciones
y2023_pred = algoritmo.predict(X2023_test)

# Calcular métricas de rendimiento
matriz2023 = confusion_matrix(y2023_test, y2023_pred)
print('Matriz de Confusión:')
print(matriz2023)

exactitud2023 = accuracy_score(y2023_test, y2023_pred)
print('Exactitud del modelo:', exactitud2023)

precision2023 = precision_score(y2023_test, y2023_pred, average="binary", pos_label=1)
print('Precisión del modelo:', precision2023)

sensibilidad2023 = recall_score(y2023_test, y2023_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo:', sensibilidad2023)


Matriz de Confusión:
[[14 48]
 [24 37]]
Exactitud del modelo: 0.4146341463414634
Precisión del modelo: 0.43529411764705883
Sensibilidad del modelo: 0.6065573770491803


In [ ]:
# Crear un diccionario con los resultados
resultados = {'Exactitud': [exactitud2023],
              'Sensibilidad': [sensibilidad2023],
              'Precisión': [precision2023]}

# Convertir el diccionario en un DataFrame de pandas
tabla_resultados23 = pd.DataFrame(resultados)

# Establecer un índice descriptivo para la tabla
tabla_resultados23.index = ['Modelo 2023']

# Imprimir la tabla de resultados
print(tabla_resultados23)

             Exactitud  Sensibilidad  Precisión
Modelo 2023   0.414634      0.606557   0.435294


In [ ]:
# Combinar los DataFrames individuales en un solo DataFrame
resultados_combinados = pd.concat([tabla_resultados20, tabla_resultados21, tabla_resultados22, tabla_resultados23])

# Imprimir el DataFrame combinado
print(resultados_combinados)


             Exactitud  Sensibilidad  Precisión
Modelo 2020   0.563310      0.000000   0.000000
Modelo 2021   0.506037      0.786364   0.492877
Modelo 2022   0.465006      0.670561   0.480737
Modelo 2023   0.414634      0.606557   0.435294
